# Generated by Django 3.1.7 on 2021-04-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartments_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='address',
            field=models.TextField(),
        ),
    ]
