# Generated by Django 3.1.7 on 2021-04-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_auto_20210418_1437'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='apartments.apartments'),
        ),
    ]
